---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-json-config
data:
  {{- range $path, $_ := .Files.Glob "characters/*.json" }}
  {{ $path | base }}: |
    {{- $.Files.Get $path | nindent 4 }}
  {{- end }}