---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eliza-client
spec:
  replicas: {{ .Values.client.replicas }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: eliza-client
          image: {{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.client.port }}
          command: ["pnpm", "start:client", "--host", "0.0.0.0"]
      imagePullSecrets:
        - name: {{ .Values.client.dockerSecret }}