---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eliza-agent
spec:
  replicas: {{ .Values.agent.replicas }}
  selector:
    matchLabels:
      app: agent
  serviceName: "eliza-agent-svc"
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: eliza-agent
          image: {{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.agent.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.agent.envSecret }}
          command: ["pnpm", "start", "--character=\"characters/{{ .Values.agent.characterFile }}\""]
          volumeMounts:
            - name: tweet-cache
              mountPath: {{ .Values.agent.volumes.tweetCache.path }}
            - name: sqlite-db
              mountPath: {{ .Values.agent.volumes.sqliteDb.path }}
            - name: characters-volume
              mountPath: /app/agent/characters/{{ .Values.agent.characterFile }}
              subPath: {{ .Values.agent.characterFile }}
      imagePullSecrets:
        - name: {{ .Values.agent.dockerSecret }}
      volumes:
        - name: tweet-cache
          emptyDir: {}
        - name: characters-volume
          configMap:
            name: {{ .Values.agent.characterConfigMap }}
  volumeClaimTemplates:
    - metadata:
        name: sqlite-db
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.agent.volumes.sqliteDb.size }}